apiVersion: ENC[AES256_GCM,data:1xM=,iv:lGN+R1NRY6BCUOH/P2i8oMhyIotYTmRoqGIqO63vE6M=,tag:JFUr3RE9GA2i/3ycq6iLTA==,type:str]
kind: ENC[AES256_GCM,data:hE700Acm,iv:wV7+HlAJ4erMXo1LasWsM9tzcZqB5S3LD1YXEuLYEJ8=,tag:mkSKk4jdZBd8qFlC/en5Bg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:w7YjUWtujj+7TLHzhto=,iv:njUCiGCu1VRo6fglOcgNWfTPJ9sx+eRuBeEsCrBZ3ao=,tag:toVmxbq6zq1tsGtNjoSvZQ==,type:str]
    namespace: ENC[AES256_GCM,data:zbqYgqhIOHLGYv8=,iv:CsV8BMD/NChi9QB5dcQLVzUZ7ar9d5m7HLoTSmJB+TI=,tag:LMNpH1nw2lijYmWLD9AQfg==,type:str]
type: ENC[AES256_GCM,data:JRLp+t3G93sp3MppoNtKMvaxxnnXmCn14HAFHtij,iv:Yzs44bxJbVgLDHE7S8zvDwTf/5liFdmTYSvEEbOgoEU=,tag:0xT0OaVHun40h45s//X6sw==,type:str]
data:
    .dockerconfigjson: ENC[AES256_GCM,data:q029/JkXe1kWIk5t1nVOv44D9VhyclB+7mWDmDJCM0leRaCORixDVaqaXEZFwAY53bZOWXSBMGWD1ykd+RspmteWRcvKIzrteF/dclzwOtofp278NANrIKaAE88ejpUQzhqvT1Hd7YuwprS/NQoABnw+kw2t9Jf0or+CQS+JcPd30dTvtOqkrtyQXP5RHYEtM/vsZ3HfZ388lk10LEcRn071lTRN2lR++0vrRHBqe0weyFLKYLtnQq+52JNm2WImo44ZNPNMsVIduH3H,iv:AwuOyULh8odWz6kV3yNjhHLeLh5cy4rbG9q+3WEcH0M=,tag:3KpHKsRgiTg8Sew4mhKhhg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1u74ps32m3mcvd6zjaw8w2p3wwfucz0r2rxrsxmq8ldlyv5lapgkqle505u
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQRGo4TVRPSzhrclZWQXBV
            MEpaSnhHeWJiVFV6c25TQWordXRHODBOSmkwCmtqU2xNSnc0eVR2bk1IdFJnKzBl
            bDNuQTh3OVMxUXlMUGdiaFJxSlZML2MKLS0tIGFwOGp2Ky9UZk4wdEwwOGZOdEJ2
            Q2MzTkJ2dWg3RCthZkwrclNjQ05xWFkKOfkjyT6A7BjLrIYmxCChj/YHXXPGLL5L
            lURWTK5UAwpOfAp2b9CYLJylrh8yp7Td71b6hHIwby1SxnCm3u6y+Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-18T16:50:29Z"
    mac: ENC[AES256_GCM,data:k6RwnokiFs63kCyJv2+DAtLvQS1F08KdDhat7WFKmvbCLMGmwU6MaxiPlgjKn2XjGpL86k0d2CQksYXOVVAHNIBGt3Jle1UjaPFfF44iQJsvIgxTvOnyG74gkARVeEwVENPMgHHLfPSUkIe4eE94NBag8onHmpyY4yQvl6kgSWc=,iv:C78aRvtQ4w6wLm88L7yVClJTixljicKLn9n8wy0I320=,tag:wrct8AkVXf0S7tLFAp4Xkw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
